/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CareerCreate,
  DeleteApiV10CareerId200,
  GetApiV10CareerId200,
  GetApiV10CareerParams,
  PostApiV10Career200,
  PutApiV10CareerId200,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single career record by its ID
 * @summary Get career by ID
 */
export const getApiV10CareerId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10CareerId200>(
      {url: `/api/v1.0/career/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10CareerIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/career/${id}`
    ] as const;
    }

export const getGetApiV10CareerIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/career/${id}`
    ] as const;
    }

    
export const getGetApiV10CareerIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CareerId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CareerIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10CareerId>>> = ({ signal }) => getApiV10CareerId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CareerIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10CareerId>>>
export type GetApiV10CareerIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10CareerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CareerId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CareerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CareerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CareerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CareerId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CareerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CareerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CareerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CareerId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get career by ID
 */

export function useGetApiV10CareerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CareerId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CareerIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get career by ID
 */
export const prefetchGetApiV10CareerIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10CareerId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CareerIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10CareerIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10CareerId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CareerIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10CareerId>>> = ({ signal }) => getApiV10CareerId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CareerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10CareerId>>>
export type GetApiV10CareerIdQueryError = ErrorType<void>


export function useGetApiV10CareerId<TData = Awaited<ReturnType<typeof getApiV10CareerId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CareerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CareerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CareerId<TData = Awaited<ReturnType<typeof getApiV10CareerId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CareerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CareerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CareerId<TData = Awaited<ReturnType<typeof getApiV10CareerId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get career by ID
 */

export function useGetApiV10CareerId<TData = Awaited<ReturnType<typeof getApiV10CareerId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CareerIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get career by ID
 */
export const prefetchGetApiV10CareerIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10CareerId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CareerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CareerIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single career record by its ID
 * @summary Update career by ID
 */
export const putApiV10CareerId = (
    id: string,
    careerCreate: BodyType<CareerCreate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PutApiV10CareerId200>(
      {url: `/api/v1.0/career/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: careerCreate
    },
      options);
    }
  


export const getPutApiV10CareerIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10CareerId>>, TError,{id: string;data: BodyType<CareerCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10CareerId>>, TError,{id: string;data: BodyType<CareerCreate>}, TContext> => {

const mutationKey = ['putApiV10CareerId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10CareerId>>, {id: string;data: BodyType<CareerCreate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10CareerId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10CareerIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10CareerId>>>
    export type PutApiV10CareerIdMutationBody = BodyType<CareerCreate>
    export type PutApiV10CareerIdMutationError = ErrorType<void>

    /**
 * @summary Update career by ID
 */
export const usePutApiV10CareerId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10CareerId>>, TError,{id: string;data: BodyType<CareerCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10CareerId>>,
        TError,
        {id: string;data: BodyType<CareerCreate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10CareerIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single career record by its ID
 * @summary Delete career by ID
 */
export const deleteApiV10CareerId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10CareerId200>(
      {url: `/api/v1.0/career/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10CareerIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10CareerId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10CareerId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10CareerId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10CareerId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10CareerId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10CareerIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10CareerId>>>
    
    export type DeleteApiV10CareerIdMutationError = ErrorType<void>

    /**
 * @summary Delete career by ID
 */
export const useDeleteApiV10CareerId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10CareerId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10CareerId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10CareerIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of career with pagination, filtering and sorting
 * @summary Get all career
 */
export const getApiV10Career = (
    params?: GetApiV10CareerParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/career`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10CareerInfiniteQueryKey = (params?: GetApiV10CareerParams,) => {
    return [
    'infinite', `/api/v1.0/career`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10CareerQueryKey = (params?: GetApiV10CareerParams,) => {
    return [
    `/api/v1.0/career`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10CareerInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Career>>>, TError = ErrorType<unknown>>(params?: GetApiV10CareerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CareerInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Career>>> = ({ signal }) => getApiV10Career(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CareerInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Career>>>
export type GetApiV10CareerInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10CareerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Career>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10CareerParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Career>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Career>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CareerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Career>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CareerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Career>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Career>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CareerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Career>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CareerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all career
 */

export function useGetApiV10CareerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Career>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CareerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CareerInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all career
 */
export const prefetchGetApiV10CareerInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Career>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10CareerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CareerInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10CareerQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Career>>, TError = ErrorType<unknown>>(params?: GetApiV10CareerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CareerQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Career>>> = ({ signal }) => getApiV10Career(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CareerQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Career>>>
export type GetApiV10CareerQueryError = ErrorType<unknown>


export function useGetApiV10Career<TData = Awaited<ReturnType<typeof getApiV10Career>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10CareerParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Career>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Career>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Career<TData = Awaited<ReturnType<typeof getApiV10Career>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CareerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Career>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Career>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Career<TData = Awaited<ReturnType<typeof getApiV10Career>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CareerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all career
 */

export function useGetApiV10Career<TData = Awaited<ReturnType<typeof getApiV10Career>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CareerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CareerQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all career
 */
export const prefetchGetApiV10CareerQuery = async <TData = Awaited<ReturnType<typeof getApiV10Career>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10CareerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Career>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CareerQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new career record
 * @summary Create a career
 */
export const postApiV10Career = (
    careerCreate: BodyType<CareerCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10Career200>(
      {url: `/api/v1.0/career`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: careerCreate, signal
    },
      options);
    }
  


export const getPostApiV10CareerMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Career>>, TError,{data: BodyType<CareerCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Career>>, TError,{data: BodyType<CareerCreate>}, TContext> => {

const mutationKey = ['postApiV10Career'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Career>>, {data: BodyType<CareerCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Career(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10CareerMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Career>>>
    export type PostApiV10CareerMutationBody = BodyType<CareerCreate>
    export type PostApiV10CareerMutationError = ErrorType<unknown>

    /**
 * @summary Create a career
 */
export const usePostApiV10Career = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Career>>, TError,{data: BodyType<CareerCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Career>>,
        TError,
        {data: BodyType<CareerCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10CareerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    