/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CaseStudyCreate,
  DeleteApiV10CaseStudyId200,
  GetApiV10CaseStudyId200,
  GetApiV10CaseStudyParams,
  PostApiV10CaseStudy200,
  PutApiV10CaseStudyId200,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single caseStudy record by its ID
 * @summary Get caseStudy by ID
 */
export const getApiV10CaseStudyId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10CaseStudyId200>(
      {url: `/api/v1.0/caseStudy/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10CaseStudyIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/caseStudy/${id}`
    ] as const;
    }

export const getGetApiV10CaseStudyIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/caseStudy/${id}`
    ] as const;
    }

    
export const getGetApiV10CaseStudyIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CaseStudyId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CaseStudyIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10CaseStudyId>>> = ({ signal }) => getApiV10CaseStudyId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CaseStudyIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10CaseStudyId>>>
export type GetApiV10CaseStudyIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10CaseStudyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CaseStudyId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CaseStudyId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CaseStudyId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CaseStudyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CaseStudyId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CaseStudyId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CaseStudyId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CaseStudyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CaseStudyId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get caseStudy by ID
 */

export function useGetApiV10CaseStudyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CaseStudyId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CaseStudyIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get caseStudy by ID
 */
export const prefetchGetApiV10CaseStudyIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CaseStudyIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10CaseStudyIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CaseStudyIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10CaseStudyId>>> = ({ signal }) => getApiV10CaseStudyId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CaseStudyIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10CaseStudyId>>>
export type GetApiV10CaseStudyIdQueryError = ErrorType<void>


export function useGetApiV10CaseStudyId<TData = Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CaseStudyId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CaseStudyId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CaseStudyId<TData = Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CaseStudyId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CaseStudyId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CaseStudyId<TData = Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get caseStudy by ID
 */

export function useGetApiV10CaseStudyId<TData = Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CaseStudyIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get caseStudy by ID
 */
export const prefetchGetApiV10CaseStudyIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CaseStudyIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single caseStudy record by its ID
 * @summary Update caseStudy by ID
 */
export const putApiV10CaseStudyId = (
    id: string,
    caseStudyCreate: BodyType<CaseStudyCreate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PutApiV10CaseStudyId200>(
      {url: `/api/v1.0/caseStudy/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: caseStudyCreate
    },
      options);
    }
  


export const getPutApiV10CaseStudyIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10CaseStudyId>>, TError,{id: string;data: BodyType<CaseStudyCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10CaseStudyId>>, TError,{id: string;data: BodyType<CaseStudyCreate>}, TContext> => {

const mutationKey = ['putApiV10CaseStudyId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10CaseStudyId>>, {id: string;data: BodyType<CaseStudyCreate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10CaseStudyId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10CaseStudyIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10CaseStudyId>>>
    export type PutApiV10CaseStudyIdMutationBody = BodyType<CaseStudyCreate>
    export type PutApiV10CaseStudyIdMutationError = ErrorType<void>

    /**
 * @summary Update caseStudy by ID
 */
export const usePutApiV10CaseStudyId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10CaseStudyId>>, TError,{id: string;data: BodyType<CaseStudyCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10CaseStudyId>>,
        TError,
        {id: string;data: BodyType<CaseStudyCreate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10CaseStudyIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single caseStudy record by its ID
 * @summary Delete caseStudy by ID
 */
export const deleteApiV10CaseStudyId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10CaseStudyId200>(
      {url: `/api/v1.0/caseStudy/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10CaseStudyIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10CaseStudyId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10CaseStudyId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10CaseStudyId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10CaseStudyId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10CaseStudyId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10CaseStudyIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10CaseStudyId>>>
    
    export type DeleteApiV10CaseStudyIdMutationError = ErrorType<void>

    /**
 * @summary Delete caseStudy by ID
 */
export const useDeleteApiV10CaseStudyId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10CaseStudyId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10CaseStudyId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10CaseStudyIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of caseStudy with pagination, filtering and sorting
 * @summary Get all caseStudy
 */
export const getApiV10CaseStudy = (
    params?: GetApiV10CaseStudyParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/caseStudy`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10CaseStudyInfiniteQueryKey = (params?: GetApiV10CaseStudyParams,) => {
    return [
    'infinite', `/api/v1.0/caseStudy`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10CaseStudyQueryKey = (params?: GetApiV10CaseStudyParams,) => {
    return [
    `/api/v1.0/caseStudy`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10CaseStudyInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CaseStudy>>>, TError = ErrorType<unknown>>(params?: GetApiV10CaseStudyParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CaseStudyInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10CaseStudy>>> = ({ signal }) => getApiV10CaseStudy(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CaseStudyInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10CaseStudy>>>
export type GetApiV10CaseStudyInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10CaseStudyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CaseStudy>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10CaseStudyParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CaseStudy>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CaseStudy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CaseStudyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CaseStudy>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CaseStudyParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CaseStudy>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CaseStudy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CaseStudyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CaseStudy>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CaseStudyParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all caseStudy
 */

export function useGetApiV10CaseStudyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10CaseStudy>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CaseStudyParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CaseStudyInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all caseStudy
 */
export const prefetchGetApiV10CaseStudyInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10CaseStudyParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CaseStudyInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10CaseStudyQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError = ErrorType<unknown>>(params?: GetApiV10CaseStudyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10CaseStudyQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10CaseStudy>>> = ({ signal }) => getApiV10CaseStudy(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10CaseStudyQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10CaseStudy>>>
export type GetApiV10CaseStudyQueryError = ErrorType<unknown>


export function useGetApiV10CaseStudy<TData = Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10CaseStudyParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CaseStudy>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CaseStudy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CaseStudy<TData = Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CaseStudyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10CaseStudy>>,
          TError,
          Awaited<ReturnType<typeof getApiV10CaseStudy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10CaseStudy<TData = Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CaseStudyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all caseStudy
 */

export function useGetApiV10CaseStudy<TData = Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError = ErrorType<unknown>>(
 params?: GetApiV10CaseStudyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10CaseStudyQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all caseStudy
 */
export const prefetchGetApiV10CaseStudyQuery = async <TData = Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10CaseStudyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10CaseStudy>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10CaseStudyQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new caseStudy record
 * @summary Create a caseStudy
 */
export const postApiV10CaseStudy = (
    caseStudyCreate: BodyType<CaseStudyCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10CaseStudy200>(
      {url: `/api/v1.0/caseStudy`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: caseStudyCreate, signal
    },
      options);
    }
  


export const getPostApiV10CaseStudyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10CaseStudy>>, TError,{data: BodyType<CaseStudyCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10CaseStudy>>, TError,{data: BodyType<CaseStudyCreate>}, TContext> => {

const mutationKey = ['postApiV10CaseStudy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10CaseStudy>>, {data: BodyType<CaseStudyCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10CaseStudy(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10CaseStudyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10CaseStudy>>>
    export type PostApiV10CaseStudyMutationBody = BodyType<CaseStudyCreate>
    export type PostApiV10CaseStudyMutationError = ErrorType<unknown>

    /**
 * @summary Create a caseStudy
 */
export const usePostApiV10CaseStudy = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10CaseStudy>>, TError,{data: BodyType<CaseStudyCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10CaseStudy>>,
        TError,
        {data: BodyType<CaseStudyCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10CaseStudyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    