/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FooterMutate,
  GetApiV10FooterId200,
  GetApiV10FooterParams,
  PostApiV10Footer200,
  PutApiV10FooterId200,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single footer record by its ID with nested columns, rows and elements
 * @summary Get footer by ID
 */
export const getApiV10FooterId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10FooterId200>(
      {url: `/api/v1.0/footer/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10FooterIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/footer/${id}`
    ] as const;
    }

export const getGetApiV10FooterIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/footer/${id}`
    ] as const;
    }

    
export const getGetApiV10FooterIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10FooterId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10FooterIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10FooterId>>> = ({ signal }) => getApiV10FooterId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10FooterIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10FooterId>>>
export type GetApiV10FooterIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10FooterIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10FooterId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10FooterId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10FooterId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10FooterIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10FooterId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10FooterId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10FooterId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10FooterIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10FooterId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get footer by ID
 */

export function useGetApiV10FooterIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10FooterId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10FooterIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get footer by ID
 */
export const prefetchGetApiV10FooterIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10FooterId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10FooterIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10FooterIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10FooterId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10FooterIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10FooterId>>> = ({ signal }) => getApiV10FooterId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10FooterIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10FooterId>>>
export type GetApiV10FooterIdQueryError = ErrorType<void>


export function useGetApiV10FooterId<TData = Awaited<ReturnType<typeof getApiV10FooterId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10FooterId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10FooterId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10FooterId<TData = Awaited<ReturnType<typeof getApiV10FooterId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10FooterId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10FooterId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10FooterId<TData = Awaited<ReturnType<typeof getApiV10FooterId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get footer by ID
 */

export function useGetApiV10FooterId<TData = Awaited<ReturnType<typeof getApiV10FooterId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10FooterIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get footer by ID
 */
export const prefetchGetApiV10FooterIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10FooterId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10FooterId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10FooterIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single footer record by its ID. The nested columns/rows/elements tree is fully replaced.
 * @summary Update footer by ID
 */
export const putApiV10FooterId = (
    id: string,
    footerMutate: BodyType<FooterMutate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PutApiV10FooterId200>(
      {url: `/api/v1.0/footer/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: footerMutate
    },
      options);
    }
  


export const getPutApiV10FooterIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10FooterId>>, TError,{id: string;data: BodyType<FooterMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10FooterId>>, TError,{id: string;data: BodyType<FooterMutate>}, TContext> => {

const mutationKey = ['putApiV10FooterId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10FooterId>>, {id: string;data: BodyType<FooterMutate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10FooterId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10FooterIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10FooterId>>>
    export type PutApiV10FooterIdMutationBody = BodyType<FooterMutate>
    export type PutApiV10FooterIdMutationError = ErrorType<void>

    /**
 * @summary Update footer by ID
 */
export const usePutApiV10FooterId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10FooterId>>, TError,{id: string;data: BodyType<FooterMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10FooterId>>,
        TError,
        {id: string;data: BodyType<FooterMutate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10FooterIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single footer record by its ID including all nested columns, rows and elements
 * @summary Delete footer by ID
 */
export const deleteApiV10FooterId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/footer/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10FooterIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10FooterId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10FooterId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10FooterId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10FooterId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10FooterId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10FooterIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10FooterId>>>
    
    export type DeleteApiV10FooterIdMutationError = ErrorType<void>

    /**
 * @summary Delete footer by ID
 */
export const useDeleteApiV10FooterId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10FooterId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10FooterId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10FooterIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of footers with pagination, filtering and sorting. Pass ?language=vi|en to filter by language.
 * @summary Get all footers
 */
export const getApiV10Footer = (
    params?: GetApiV10FooterParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/footer`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10FooterInfiniteQueryKey = (params?: GetApiV10FooterParams,) => {
    return [
    'infinite', `/api/v1.0/footer`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10FooterQueryKey = (params?: GetApiV10FooterParams,) => {
    return [
    `/api/v1.0/footer`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10FooterInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Footer>>>, TError = ErrorType<unknown>>(params?: GetApiV10FooterParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10FooterInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Footer>>> = ({ signal }) => getApiV10Footer(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10FooterInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Footer>>>
export type GetApiV10FooterInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10FooterInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Footer>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10FooterParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Footer>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Footer>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10FooterInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Footer>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10FooterParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Footer>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Footer>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10FooterInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Footer>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10FooterParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all footers
 */

export function useGetApiV10FooterInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Footer>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10FooterParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10FooterInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all footers
 */
export const prefetchGetApiV10FooterInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Footer>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10FooterParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10FooterInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10FooterQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Footer>>, TError = ErrorType<unknown>>(params?: GetApiV10FooterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10FooterQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Footer>>> = ({ signal }) => getApiV10Footer(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10FooterQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Footer>>>
export type GetApiV10FooterQueryError = ErrorType<unknown>


export function useGetApiV10Footer<TData = Awaited<ReturnType<typeof getApiV10Footer>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10FooterParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Footer>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Footer>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Footer<TData = Awaited<ReturnType<typeof getApiV10Footer>>, TError = ErrorType<unknown>>(
 params?: GetApiV10FooterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Footer>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Footer>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Footer<TData = Awaited<ReturnType<typeof getApiV10Footer>>, TError = ErrorType<unknown>>(
 params?: GetApiV10FooterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all footers
 */

export function useGetApiV10Footer<TData = Awaited<ReturnType<typeof getApiV10Footer>>, TError = ErrorType<unknown>>(
 params?: GetApiV10FooterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10FooterQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all footers
 */
export const prefetchGetApiV10FooterQuery = async <TData = Awaited<ReturnType<typeof getApiV10Footer>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10FooterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Footer>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10FooterQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new footer record with nested columns, rows and elements
 * @summary Create a footer
 */
export const postApiV10Footer = (
    footerMutate: BodyType<FooterMutate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10Footer200>(
      {url: `/api/v1.0/footer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: footerMutate, signal
    },
      options);
    }
  


export const getPostApiV10FooterMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Footer>>, TError,{data: BodyType<FooterMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Footer>>, TError,{data: BodyType<FooterMutate>}, TContext> => {

const mutationKey = ['postApiV10Footer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Footer>>, {data: BodyType<FooterMutate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Footer(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10FooterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Footer>>>
    export type PostApiV10FooterMutationBody = BodyType<FooterMutate>
    export type PostApiV10FooterMutationError = ErrorType<unknown>

    /**
 * @summary Create a footer
 */
export const usePostApiV10Footer = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Footer>>, TError,{data: BodyType<FooterMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Footer>>,
        TError,
        {data: BodyType<FooterMutate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10FooterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    