/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV10IndustryId200,
  GetApiV10IndustryId200,
  GetApiV10IndustryParams,
  IndustryCreate,
  PostApiV10Industry200,
  PutApiV10IndustryId200,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single industry record by its ID
 * @summary Get industry by ID
 */
export const getApiV10IndustryId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10IndustryId200>(
      {url: `/api/v1.0/industry/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10IndustryIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/industry/${id}`
    ] as const;
    }

export const getGetApiV10IndustryIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/industry/${id}`
    ] as const;
    }

    
export const getGetApiV10IndustryIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10IndustryId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10IndustryIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10IndustryId>>> = ({ signal }) => getApiV10IndustryId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10IndustryIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10IndustryId>>>
export type GetApiV10IndustryIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10IndustryIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10IndustryId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10IndustryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10IndustryId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10IndustryIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10IndustryId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10IndustryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10IndustryId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10IndustryIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10IndustryId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get industry by ID
 */

export function useGetApiV10IndustryIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10IndustryId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10IndustryIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get industry by ID
 */
export const prefetchGetApiV10IndustryIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10IndustryId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10IndustryIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10IndustryIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10IndustryId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10IndustryIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10IndustryId>>> = ({ signal }) => getApiV10IndustryId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10IndustryIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10IndustryId>>>
export type GetApiV10IndustryIdQueryError = ErrorType<void>


export function useGetApiV10IndustryId<TData = Awaited<ReturnType<typeof getApiV10IndustryId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10IndustryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10IndustryId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10IndustryId<TData = Awaited<ReturnType<typeof getApiV10IndustryId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10IndustryId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10IndustryId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10IndustryId<TData = Awaited<ReturnType<typeof getApiV10IndustryId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get industry by ID
 */

export function useGetApiV10IndustryId<TData = Awaited<ReturnType<typeof getApiV10IndustryId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10IndustryIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get industry by ID
 */
export const prefetchGetApiV10IndustryIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10IndustryId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10IndustryId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10IndustryIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single industry record by its ID
 * @summary Update industry by ID
 */
export const putApiV10IndustryId = (
    id: string,
    industryCreate: BodyType<IndustryCreate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PutApiV10IndustryId200>(
      {url: `/api/v1.0/industry/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: industryCreate
    },
      options);
    }
  


export const getPutApiV10IndustryIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10IndustryId>>, TError,{id: string;data: BodyType<IndustryCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10IndustryId>>, TError,{id: string;data: BodyType<IndustryCreate>}, TContext> => {

const mutationKey = ['putApiV10IndustryId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10IndustryId>>, {id: string;data: BodyType<IndustryCreate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10IndustryId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10IndustryIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10IndustryId>>>
    export type PutApiV10IndustryIdMutationBody = BodyType<IndustryCreate>
    export type PutApiV10IndustryIdMutationError = ErrorType<void>

    /**
 * @summary Update industry by ID
 */
export const usePutApiV10IndustryId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10IndustryId>>, TError,{id: string;data: BodyType<IndustryCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10IndustryId>>,
        TError,
        {id: string;data: BodyType<IndustryCreate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10IndustryIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single industry record by its ID
 * @summary Delete industry by ID
 */
export const deleteApiV10IndustryId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10IndustryId200>(
      {url: `/api/v1.0/industry/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10IndustryIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10IndustryId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10IndustryId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10IndustryId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10IndustryId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10IndustryId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10IndustryIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10IndustryId>>>
    
    export type DeleteApiV10IndustryIdMutationError = ErrorType<void>

    /**
 * @summary Delete industry by ID
 */
export const useDeleteApiV10IndustryId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10IndustryId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10IndustryId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10IndustryIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of industry with pagination, filtering and sorting
 * @summary Get all industry
 */
export const getApiV10Industry = (
    params?: GetApiV10IndustryParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/industry`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10IndustryInfiniteQueryKey = (params?: GetApiV10IndustryParams,) => {
    return [
    'infinite', `/api/v1.0/industry`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10IndustryQueryKey = (params?: GetApiV10IndustryParams,) => {
    return [
    `/api/v1.0/industry`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10IndustryInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Industry>>>, TError = ErrorType<unknown>>(params?: GetApiV10IndustryParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10IndustryInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Industry>>> = ({ signal }) => getApiV10Industry(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10IndustryInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Industry>>>
export type GetApiV10IndustryInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10IndustryInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Industry>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10IndustryParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Industry>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Industry>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10IndustryInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Industry>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10IndustryParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Industry>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Industry>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10IndustryInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Industry>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10IndustryParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all industry
 */

export function useGetApiV10IndustryInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Industry>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10IndustryParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10IndustryInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all industry
 */
export const prefetchGetApiV10IndustryInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Industry>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10IndustryParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10IndustryInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10IndustryQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Industry>>, TError = ErrorType<unknown>>(params?: GetApiV10IndustryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10IndustryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Industry>>> = ({ signal }) => getApiV10Industry(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10IndustryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Industry>>>
export type GetApiV10IndustryQueryError = ErrorType<unknown>


export function useGetApiV10Industry<TData = Awaited<ReturnType<typeof getApiV10Industry>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10IndustryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Industry>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Industry>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Industry<TData = Awaited<ReturnType<typeof getApiV10Industry>>, TError = ErrorType<unknown>>(
 params?: GetApiV10IndustryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Industry>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Industry>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Industry<TData = Awaited<ReturnType<typeof getApiV10Industry>>, TError = ErrorType<unknown>>(
 params?: GetApiV10IndustryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all industry
 */

export function useGetApiV10Industry<TData = Awaited<ReturnType<typeof getApiV10Industry>>, TError = ErrorType<unknown>>(
 params?: GetApiV10IndustryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10IndustryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all industry
 */
export const prefetchGetApiV10IndustryQuery = async <TData = Awaited<ReturnType<typeof getApiV10Industry>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10IndustryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Industry>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10IndustryQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new industry record
 * @summary Create a industry
 */
export const postApiV10Industry = (
    industryCreate: BodyType<IndustryCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10Industry200>(
      {url: `/api/v1.0/industry`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: industryCreate, signal
    },
      options);
    }
  


export const getPostApiV10IndustryMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Industry>>, TError,{data: BodyType<IndustryCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Industry>>, TError,{data: BodyType<IndustryCreate>}, TContext> => {

const mutationKey = ['postApiV10Industry'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Industry>>, {data: BodyType<IndustryCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Industry(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10IndustryMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Industry>>>
    export type PostApiV10IndustryMutationBody = BodyType<IndustryCreate>
    export type PostApiV10IndustryMutationError = ErrorType<unknown>

    /**
 * @summary Create a industry
 */
export const usePostApiV10Industry = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Industry>>, TError,{data: BodyType<IndustryCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Industry>>,
        TError,
        {data: BodyType<IndustryCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10IndustryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    