/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV10LeadershipId200,
  GetApiV10LeadershipId200,
  GetApiV10LeadershipParams,
  LeadershipCreate,
  PostApiV10Leadership200,
  PutApiV10LeadershipId200,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single leadership record by its ID
 * @summary Get leadership by ID
 */
export const getApiV10LeadershipId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10LeadershipId200>(
      {url: `/api/v1.0/leadership/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10LeadershipIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/leadership/${id}`
    ] as const;
    }

export const getGetApiV10LeadershipIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/leadership/${id}`
    ] as const;
    }

    
export const getGetApiV10LeadershipIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LeadershipId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LeadershipIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10LeadershipId>>> = ({ signal }) => getApiV10LeadershipId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LeadershipIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10LeadershipId>>>
export type GetApiV10LeadershipIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10LeadershipIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LeadershipId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LeadershipId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LeadershipId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeadershipIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LeadershipId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LeadershipId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LeadershipId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeadershipIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LeadershipId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get leadership by ID
 */

export function useGetApiV10LeadershipIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LeadershipId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LeadershipIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get leadership by ID
 */
export const prefetchGetApiV10LeadershipIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LeadershipIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10LeadershipIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LeadershipIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10LeadershipId>>> = ({ signal }) => getApiV10LeadershipId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LeadershipIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10LeadershipId>>>
export type GetApiV10LeadershipIdQueryError = ErrorType<void>


export function useGetApiV10LeadershipId<TData = Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LeadershipId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LeadershipId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeadershipId<TData = Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LeadershipId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LeadershipId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeadershipId<TData = Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get leadership by ID
 */

export function useGetApiV10LeadershipId<TData = Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LeadershipIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get leadership by ID
 */
export const prefetchGetApiV10LeadershipIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeadershipId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LeadershipIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single leadership record by its ID
 * @summary Update leadership by ID
 */
export const putApiV10LeadershipId = (
    id: string,
    leadershipCreate: BodyType<LeadershipCreate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PutApiV10LeadershipId200>(
      {url: `/api/v1.0/leadership/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: leadershipCreate
    },
      options);
    }
  


export const getPutApiV10LeadershipIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10LeadershipId>>, TError,{id: string;data: BodyType<LeadershipCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10LeadershipId>>, TError,{id: string;data: BodyType<LeadershipCreate>}, TContext> => {

const mutationKey = ['putApiV10LeadershipId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10LeadershipId>>, {id: string;data: BodyType<LeadershipCreate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10LeadershipId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10LeadershipIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10LeadershipId>>>
    export type PutApiV10LeadershipIdMutationBody = BodyType<LeadershipCreate>
    export type PutApiV10LeadershipIdMutationError = ErrorType<void>

    /**
 * @summary Update leadership by ID
 */
export const usePutApiV10LeadershipId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10LeadershipId>>, TError,{id: string;data: BodyType<LeadershipCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10LeadershipId>>,
        TError,
        {id: string;data: BodyType<LeadershipCreate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10LeadershipIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single leadership record by its ID
 * @summary Delete leadership by ID
 */
export const deleteApiV10LeadershipId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10LeadershipId200>(
      {url: `/api/v1.0/leadership/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10LeadershipIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10LeadershipId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10LeadershipId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10LeadershipId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10LeadershipId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10LeadershipId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10LeadershipIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10LeadershipId>>>
    
    export type DeleteApiV10LeadershipIdMutationError = ErrorType<void>

    /**
 * @summary Delete leadership by ID
 */
export const useDeleteApiV10LeadershipId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10LeadershipId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10LeadershipId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10LeadershipIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of leadership with pagination, filtering and sorting
 * @summary Get all leadership
 */
export const getApiV10Leadership = (
    params?: GetApiV10LeadershipParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/leadership`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10LeadershipInfiniteQueryKey = (params?: GetApiV10LeadershipParams,) => {
    return [
    'infinite', `/api/v1.0/leadership`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10LeadershipQueryKey = (params?: GetApiV10LeadershipParams,) => {
    return [
    `/api/v1.0/leadership`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10LeadershipInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Leadership>>>, TError = ErrorType<unknown>>(params?: GetApiV10LeadershipParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LeadershipInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Leadership>>> = ({ signal }) => getApiV10Leadership(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LeadershipInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Leadership>>>
export type GetApiV10LeadershipInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10LeadershipInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Leadership>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10LeadershipParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Leadership>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Leadership>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeadershipInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Leadership>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeadershipParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Leadership>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Leadership>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeadershipInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Leadership>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeadershipParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all leadership
 */

export function useGetApiV10LeadershipInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Leadership>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeadershipParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LeadershipInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all leadership
 */
export const prefetchGetApiV10LeadershipInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Leadership>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10LeadershipParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LeadershipInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10LeadershipQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Leadership>>, TError = ErrorType<unknown>>(params?: GetApiV10LeadershipParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LeadershipQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Leadership>>> = ({ signal }) => getApiV10Leadership(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LeadershipQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Leadership>>>
export type GetApiV10LeadershipQueryError = ErrorType<unknown>


export function useGetApiV10Leadership<TData = Awaited<ReturnType<typeof getApiV10Leadership>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10LeadershipParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Leadership>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Leadership>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Leadership<TData = Awaited<ReturnType<typeof getApiV10Leadership>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeadershipParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Leadership>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Leadership>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Leadership<TData = Awaited<ReturnType<typeof getApiV10Leadership>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeadershipParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all leadership
 */

export function useGetApiV10Leadership<TData = Awaited<ReturnType<typeof getApiV10Leadership>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeadershipParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LeadershipQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all leadership
 */
export const prefetchGetApiV10LeadershipQuery = async <TData = Awaited<ReturnType<typeof getApiV10Leadership>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10LeadershipParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leadership>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LeadershipQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new leadership record
 * @summary Create a leadership
 */
export const postApiV10Leadership = (
    leadershipCreate: BodyType<LeadershipCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10Leadership200>(
      {url: `/api/v1.0/leadership`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: leadershipCreate, signal
    },
      options);
    }
  


export const getPostApiV10LeadershipMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Leadership>>, TError,{data: BodyType<LeadershipCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Leadership>>, TError,{data: BodyType<LeadershipCreate>}, TContext> => {

const mutationKey = ['postApiV10Leadership'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Leadership>>, {data: BodyType<LeadershipCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Leadership(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10LeadershipMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Leadership>>>
    export type PostApiV10LeadershipMutationBody = BodyType<LeadershipCreate>
    export type PostApiV10LeadershipMutationError = ErrorType<unknown>

    /**
 * @summary Create a leadership
 */
export const usePostApiV10Leadership = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Leadership>>, TError,{data: BodyType<LeadershipCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Leadership>>,
        TError,
        {data: BodyType<LeadershipCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10LeadershipMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    