/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV10ProductId200,
  GetApiV10ProductId200,
  GetApiV10ProductParams,
  PostApiV10Product200,
  ProductCreate,
  PutApiV10ProductId200,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single product record by its ID
 * @summary Get product by ID
 */
export const getApiV10ProductId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10ProductId200>(
      {url: `/api/v1.0/product/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10ProductIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/product/${id}`
    ] as const;
    }

export const getGetApiV10ProductIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/product/${id}`
    ] as const;
    }

    
export const getGetApiV10ProductIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ProductId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10ProductIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10ProductId>>> = ({ signal }) => getApiV10ProductId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10ProductIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10ProductId>>>
export type GetApiV10ProductIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10ProductIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ProductId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ProductId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ProductId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ProductIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ProductId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ProductId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ProductId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ProductIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ProductId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get product by ID
 */

export function useGetApiV10ProductIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ProductId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10ProductIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get product by ID
 */
export const prefetchGetApiV10ProductIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10ProductId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10ProductIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10ProductIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10ProductId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10ProductIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10ProductId>>> = ({ signal }) => getApiV10ProductId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10ProductIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10ProductId>>>
export type GetApiV10ProductIdQueryError = ErrorType<void>


export function useGetApiV10ProductId<TData = Awaited<ReturnType<typeof getApiV10ProductId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ProductId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ProductId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ProductId<TData = Awaited<ReturnType<typeof getApiV10ProductId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ProductId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ProductId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ProductId<TData = Awaited<ReturnType<typeof getApiV10ProductId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get product by ID
 */

export function useGetApiV10ProductId<TData = Awaited<ReturnType<typeof getApiV10ProductId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10ProductIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get product by ID
 */
export const prefetchGetApiV10ProductIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10ProductId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ProductId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10ProductIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single product record by its ID
 * @summary Update product by ID
 */
export const putApiV10ProductId = (
    id: string,
    productCreate: BodyType<ProductCreate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PutApiV10ProductId200>(
      {url: `/api/v1.0/product/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: productCreate
    },
      options);
    }
  


export const getPutApiV10ProductIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10ProductId>>, TError,{id: string;data: BodyType<ProductCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10ProductId>>, TError,{id: string;data: BodyType<ProductCreate>}, TContext> => {

const mutationKey = ['putApiV10ProductId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10ProductId>>, {id: string;data: BodyType<ProductCreate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10ProductId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10ProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10ProductId>>>
    export type PutApiV10ProductIdMutationBody = BodyType<ProductCreate>
    export type PutApiV10ProductIdMutationError = ErrorType<void>

    /**
 * @summary Update product by ID
 */
export const usePutApiV10ProductId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10ProductId>>, TError,{id: string;data: BodyType<ProductCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10ProductId>>,
        TError,
        {id: string;data: BodyType<ProductCreate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10ProductIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single product record by its ID
 * @summary Delete product by ID
 */
export const deleteApiV10ProductId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10ProductId200>(
      {url: `/api/v1.0/product/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10ProductIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10ProductId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10ProductId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10ProductId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10ProductId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10ProductId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10ProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10ProductId>>>
    
    export type DeleteApiV10ProductIdMutationError = ErrorType<void>

    /**
 * @summary Delete product by ID
 */
export const useDeleteApiV10ProductId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10ProductId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10ProductId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10ProductIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of product with pagination, filtering and sorting
 * @summary Get all product
 */
export const getApiV10Product = (
    params?: GetApiV10ProductParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/product`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10ProductInfiniteQueryKey = (params?: GetApiV10ProductParams,) => {
    return [
    'infinite', `/api/v1.0/product`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10ProductQueryKey = (params?: GetApiV10ProductParams,) => {
    return [
    `/api/v1.0/product`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10ProductInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Product>>>, TError = ErrorType<unknown>>(params?: GetApiV10ProductParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10ProductInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Product>>> = ({ signal }) => getApiV10Product(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10ProductInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Product>>>
export type GetApiV10ProductInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10ProductInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Product>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10ProductParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Product>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Product>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ProductInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Product>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ProductParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Product>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Product>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ProductInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Product>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ProductParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all product
 */

export function useGetApiV10ProductInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Product>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ProductParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10ProductInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all product
 */
export const prefetchGetApiV10ProductInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Product>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10ProductParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10ProductInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10ProductQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Product>>, TError = ErrorType<unknown>>(params?: GetApiV10ProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10ProductQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Product>>> = ({ signal }) => getApiV10Product(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10ProductQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Product>>>
export type GetApiV10ProductQueryError = ErrorType<unknown>


export function useGetApiV10Product<TData = Awaited<ReturnType<typeof getApiV10Product>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10ProductParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Product>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Product>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Product<TData = Awaited<ReturnType<typeof getApiV10Product>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Product>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Product>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Product<TData = Awaited<ReturnType<typeof getApiV10Product>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all product
 */

export function useGetApiV10Product<TData = Awaited<ReturnType<typeof getApiV10Product>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10ProductQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all product
 */
export const prefetchGetApiV10ProductQuery = async <TData = Awaited<ReturnType<typeof getApiV10Product>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10ProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Product>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10ProductQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new product record
 * @summary Create a product
 */
export const postApiV10Product = (
    productCreate: BodyType<ProductCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10Product200>(
      {url: `/api/v1.0/product`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: productCreate, signal
    },
      options);
    }
  


export const getPostApiV10ProductMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Product>>, TError,{data: BodyType<ProductCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Product>>, TError,{data: BodyType<ProductCreate>}, TContext> => {

const mutationKey = ['postApiV10Product'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Product>>, {data: BodyType<ProductCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Product(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10ProductMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Product>>>
    export type PostApiV10ProductMutationBody = BodyType<ProductCreate>
    export type PostApiV10ProductMutationError = ErrorType<unknown>

    /**
 * @summary Create a product
 */
export const usePostApiV10Product = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Product>>, TError,{data: BodyType<ProductCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Product>>,
        TError,
        {data: BodyType<ProductCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10ProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    