/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV10SolutionId200,
  GetApiV10SolutionId200,
  GetApiV10SolutionParams,
  PostApiV10Solution200,
  PutApiV10SolutionId200,
  ResponseGetAllData,
  SolutionCreate
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single solution record by its ID
 * @summary Get solution by ID
 */
export const getApiV10SolutionId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10SolutionId200>(
      {url: `/api/v1.0/solution/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10SolutionIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/solution/${id}`
    ] as const;
    }

export const getGetApiV10SolutionIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/solution/${id}`
    ] as const;
    }

    
export const getGetApiV10SolutionIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SolutionId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10SolutionIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10SolutionId>>> = ({ signal }) => getApiV10SolutionId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10SolutionIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10SolutionId>>>
export type GetApiV10SolutionIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10SolutionIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SolutionId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SolutionId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SolutionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SolutionIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SolutionId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SolutionId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SolutionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SolutionIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SolutionId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get solution by ID
 */

export function useGetApiV10SolutionIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10SolutionId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10SolutionIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get solution by ID
 */
export const prefetchGetApiV10SolutionIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10SolutionId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10SolutionIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10SolutionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10SolutionId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10SolutionIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10SolutionId>>> = ({ signal }) => getApiV10SolutionId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10SolutionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10SolutionId>>>
export type GetApiV10SolutionIdQueryError = ErrorType<void>


export function useGetApiV10SolutionId<TData = Awaited<ReturnType<typeof getApiV10SolutionId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SolutionId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SolutionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SolutionId<TData = Awaited<ReturnType<typeof getApiV10SolutionId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10SolutionId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10SolutionId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SolutionId<TData = Awaited<ReturnType<typeof getApiV10SolutionId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get solution by ID
 */

export function useGetApiV10SolutionId<TData = Awaited<ReturnType<typeof getApiV10SolutionId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10SolutionIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get solution by ID
 */
export const prefetchGetApiV10SolutionIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10SolutionId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10SolutionId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10SolutionIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single solution record by its ID
 * @summary Update solution by ID
 */
export const putApiV10SolutionId = (
    id: string,
    solutionCreate: BodyType<SolutionCreate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PutApiV10SolutionId200>(
      {url: `/api/v1.0/solution/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: solutionCreate
    },
      options);
    }
  


export const getPutApiV10SolutionIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10SolutionId>>, TError,{id: string;data: BodyType<SolutionCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10SolutionId>>, TError,{id: string;data: BodyType<SolutionCreate>}, TContext> => {

const mutationKey = ['putApiV10SolutionId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10SolutionId>>, {id: string;data: BodyType<SolutionCreate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10SolutionId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10SolutionIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10SolutionId>>>
    export type PutApiV10SolutionIdMutationBody = BodyType<SolutionCreate>
    export type PutApiV10SolutionIdMutationError = ErrorType<void>

    /**
 * @summary Update solution by ID
 */
export const usePutApiV10SolutionId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10SolutionId>>, TError,{id: string;data: BodyType<SolutionCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10SolutionId>>,
        TError,
        {id: string;data: BodyType<SolutionCreate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10SolutionIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single solution record by its ID
 * @summary Delete solution by ID
 */
export const deleteApiV10SolutionId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10SolutionId200>(
      {url: `/api/v1.0/solution/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10SolutionIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10SolutionId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10SolutionId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10SolutionId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10SolutionId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10SolutionId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10SolutionIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10SolutionId>>>
    
    export type DeleteApiV10SolutionIdMutationError = ErrorType<void>

    /**
 * @summary Delete solution by ID
 */
export const useDeleteApiV10SolutionId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10SolutionId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10SolutionId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10SolutionIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of solution with pagination, filtering and sorting
 * @summary Get all solution
 */
export const getApiV10Solution = (
    params?: GetApiV10SolutionParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/solution`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10SolutionInfiniteQueryKey = (params?: GetApiV10SolutionParams,) => {
    return [
    'infinite', `/api/v1.0/solution`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10SolutionQueryKey = (params?: GetApiV10SolutionParams,) => {
    return [
    `/api/v1.0/solution`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10SolutionInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Solution>>>, TError = ErrorType<unknown>>(params?: GetApiV10SolutionParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10SolutionInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Solution>>> = ({ signal }) => getApiV10Solution(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10SolutionInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Solution>>>
export type GetApiV10SolutionInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10SolutionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Solution>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10SolutionParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Solution>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Solution>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SolutionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Solution>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SolutionParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Solution>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Solution>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10SolutionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Solution>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SolutionParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all solution
 */

export function useGetApiV10SolutionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Solution>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SolutionParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10SolutionInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all solution
 */
export const prefetchGetApiV10SolutionInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Solution>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10SolutionParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10SolutionInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10SolutionQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Solution>>, TError = ErrorType<unknown>>(params?: GetApiV10SolutionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10SolutionQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Solution>>> = ({ signal }) => getApiV10Solution(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10SolutionQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Solution>>>
export type GetApiV10SolutionQueryError = ErrorType<unknown>


export function useGetApiV10Solution<TData = Awaited<ReturnType<typeof getApiV10Solution>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10SolutionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Solution>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Solution>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Solution<TData = Awaited<ReturnType<typeof getApiV10Solution>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SolutionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Solution>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Solution>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Solution<TData = Awaited<ReturnType<typeof getApiV10Solution>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SolutionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all solution
 */

export function useGetApiV10Solution<TData = Awaited<ReturnType<typeof getApiV10Solution>>, TError = ErrorType<unknown>>(
 params?: GetApiV10SolutionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10SolutionQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all solution
 */
export const prefetchGetApiV10SolutionQuery = async <TData = Awaited<ReturnType<typeof getApiV10Solution>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10SolutionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Solution>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10SolutionQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new solution record
 * @summary Create a solution
 */
export const postApiV10Solution = (
    solutionCreate: BodyType<SolutionCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10Solution200>(
      {url: `/api/v1.0/solution`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: solutionCreate, signal
    },
      options);
    }
  


export const getPostApiV10SolutionMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Solution>>, TError,{data: BodyType<SolutionCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Solution>>, TError,{data: BodyType<SolutionCreate>}, TContext> => {

const mutationKey = ['postApiV10Solution'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Solution>>, {data: BodyType<SolutionCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Solution(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10SolutionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Solution>>>
    export type PostApiV10SolutionMutationBody = BodyType<SolutionCreate>
    export type PostApiV10SolutionMutationError = ErrorType<unknown>

    /**
 * @summary Create a solution
 */
export const usePostApiV10Solution = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Solution>>, TError,{data: BodyType<SolutionCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Solution>>,
        TError,
        {data: BodyType<SolutionCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10SolutionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    