/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

/**
 * Số lượng user đang có role và số permission đã gán
 */
export type _RoleCount = {
  users?: number;
  permissions?: number;
};
