/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { BannerCreateStatus } from './bannerCreateStatus';

export interface BannerCreate {
  /** @maxLength 255 */
  banner_name: string;
  display_order?: number;
  /** @minimum 1 */
  display_time?: number;
  status?: BannerCreateStatus;
  file_id: string;
}
