/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type CareerUpdateEmploymentType = typeof CareerUpdateEmploymentType[keyof typeof CareerUpdateEmploymentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CareerUpdateEmploymentType = {
  FULLTIME: 'FULLTIME',
  PARTTIME: 'PARTTIME',
  CONTRACT: 'CONTRACT',
  INTERNSHIP: 'INTERNSHIP',
} as const;
