/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { CareerUpdateEmploymentType } from './careerUpdateEmploymentType';

export interface CareerUpdate {
  /** @maxLength 255 */
  slug?: string;
  /** @maxLength 255 */
  title?: string;
  /**
   * @maxLength 255
   * @nullable
   */
  department?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  location?: string | null;
  employment_type?: CareerUpdateEmploymentType;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  requirements?: string | null;
  /** @nullable */
  benefits?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  salary_range?: string | null;
  sort_order?: number;
  is_active?: boolean;
  /** @nullable */
  posted_at?: string | null;
  /** @nullable */
  expired_at?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  meta_title?: string | null;
  /** @nullable */
  meta_description?: string | null;
}
