/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { CaseStudyContentStructure } from './caseStudyContentStructure';

export interface CaseStudy {
  id: string;
  /** @maxLength 255 */
  slug: string;
  /** @maxLength 255 */
  title: string;
  /**
   * @maxLength 255
   * @nullable
   */
  client_name?: string | null;
  /** @nullable */
  client_logo_id?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  content_structure?: CaseStudyContentStructure;
  /** @nullable */
  industry_id?: string | null;
  /** @nullable */
  solution_id?: string | null;
  /** @nullable */
  technology_ids?: string[] | null;
  /** @nullable */
  thumbnail_id?: string | null;
  sort_order: number;
  is_featured: boolean;
  is_active: boolean;
  /** @nullable */
  published_at?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  meta_title?: string | null;
  /** @nullable */
  meta_description?: string | null;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  updated_at: string;
  /** @nullable */
  updated_by?: string | null;
}
