/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type ContactCreateStatus = typeof ContactCreateStatus[keyof typeof ContactCreateStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContactCreateStatus = {
  new: 'new',
  seen: 'seen',
  replied: 'replied',
} as const;
