/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type ContactStatus = typeof ContactStatus[keyof typeof ContactStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContactStatus = {
  new: 'new',
  seen: 'seen',
  replied: 'replied',
} as const;
