/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { DeleteApiV10ProductId200AllOf } from './deleteApiV10ProductId200AllOf';

export type DeleteApiV10ProductId200 = ApiResponse & DeleteApiV10ProductId200AllOf;
