/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { DeleteApiV10LeadershipId200AllOf } from './deleteApiV10LeadershipId200AllOf';

export type DeleteApiV10LeadershipId200 = ApiResponse & DeleteApiV10LeadershipId200AllOf;
