/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { DeleteApiV10IndustryId200AllOf } from './deleteApiV10IndustryId200AllOf';

export type DeleteApiV10IndustryId200 = ApiResponse & DeleteApiV10IndustryId200AllOf;
