/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { FileCompressInfo } from './fileCompressInfo';
import type { FileImportInfo } from './fileImportInfo';

export interface File {
  id: string;
  /** @maxLength 500 */
  path: string;
  /** @maxLength 255 */
  original: string;
  /** @maxLength 100 */
  mime: string;
  /** @nullable */
  compress_info?: FileCompressInfo;
  /**
   * @maxLength 50
   * @nullable
   */
  compress_status?: string | null;
  /** @nullable */
  created_by?: string | null;
  /** @nullable */
  created_at?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  status?: string | null;
  /** @nullable */
  import_info?: FileImportInfo;
}
