/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { FileUpdateCompressInfo } from './fileUpdateCompressInfo';
import type { FileUpdateImportInfo } from './fileUpdateImportInfo';

export interface FileUpdate {
  /** @maxLength 500 */
  path?: string;
  /** @maxLength 255 */
  original?: string;
  /** @maxLength 100 */
  mime?: string;
  /** @nullable */
  compress_info?: FileUpdateCompressInfo;
  /**
   * @maxLength 50
   * @nullable
   */
  compress_status?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  status?: string | null;
  /** @nullable */
  import_info?: FileUpdateImportInfo;
}
