/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { FooterMutateColumnsItemRowsItem } from './footerMutateColumnsItemRowsItem';

export type FooterMutateColumnsItem = {
  /**
   * Title of the column
   * @nullable
   */
  title?: string | null;
  /**
   * Order within the footer
   * @minimum 0
   */
  sort_order?: number;
  /** Rows inside this column */
  rows?: FooterMutateColumnsItemRowsItem[];
};
