/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of the element
 */
export type FooterElementType = typeof FooterElementType[keyof typeof FooterElementType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FooterElementType = {
  text: 'text',
  image: 'image',
} as const;
