/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { FooterRow } from './footerRow';

export interface FooterColumn {
  /** Unique identifier of the footer column */
  id?: string;
  /** ID of the parent footer */
  footer_id?: string;
  /**
   * Title of the column
   * @nullable
   */
  title?: string | null;
  /**
   * Order within the footer
   * @minimum 0
   */
  sort_order?: number;
  /** Creation timestamp */
  created_at?: string;
  /**
   * Last update timestamp
   * @nullable
   */
  updated_at?: string | null;
  /** Rows inside this column */
  footer_rows?: FooterRow[];
}
