/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { FooterMutateColumnsItemRowsItemElementsItemType } from './footerMutateColumnsItemRowsItemElementsItemType';

export type FooterMutateColumnsItemRowsItemElementsItem = {
  /** Type of the element */
  type?: FooterMutateColumnsItemRowsItemElementsItemType;
  /**
   * Text content or image URL
   * @nullable
   */
  content?: string | null;
  /**
   * Optional link target
   * @nullable
   */
  link?: string | null;
  /**
   * Order within the row
   * @minimum 0
   */
  sort_order?: number;
};
