/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { FooterMutateColumnsItemRowsItemElementsItem } from './footerMutateColumnsItemRowsItemElementsItem';

export type FooterMutateColumnsItemRowsItem = {
  /** Elements (small columns) inside this row */
  elements?: FooterMutateColumnsItemRowsItemElementsItem[];
};
