/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { Footer } from './footer';

export type GetApiV10FooterId200AllOf = {
  responseData?: Footer;
};
