/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV10FooterLanguage = typeof GetApiV10FooterLanguage[keyof typeof GetApiV10FooterLanguage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV10FooterLanguage = {
  vi: 'vi',
  en: 'en',
} as const;
