/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthProfile200Data } from './getAuthProfile200Data';

export type GetAuthProfile200 = {
  success?: boolean;
  data?: GetAuthProfile200Data;
};
