/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV10PasswordResetRequestStatus } from './getApiV10PasswordResetRequestStatus';
import type { GetApiV10PasswordResetRequestSortOrder } from './getApiV10PasswordResetRequestSortOrder';

export type GetApiV10PasswordResetRequestParams = {
page?: number;
pageSize?: number;
status?: GetApiV10PasswordResetRequestStatus;
sortField?: string;
sortOrder?: GetApiV10PasswordResetRequestSortOrder;
};
