/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetApiV10PositionId200AllOf } from './getApiV10PositionId200AllOf';

export type GetApiV10PositionId200 = ApiResponse & GetApiV10PositionId200AllOf;
