/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetApiV10FileId200AllOf } from './getApiV10FileId200AllOf';

export type GetApiV10FileId200 = ApiResponse & GetApiV10FileId200AllOf;
