/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV10Term200AllOfResponseData } from './getApiV10Term200AllOfResponseData';

export type GetApiV10Term200AllOf = {
  responseData?: GetApiV10Term200AllOfResponseData;
};
