/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetApiV10RoleIdPermission200AllOf } from './getApiV10RoleIdPermission200AllOf';

export type GetApiV10RoleIdPermission200 = ApiResponse & GetApiV10RoleIdPermission200AllOf;
