/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetApiV10IndustryId200AllOf } from './getApiV10IndustryId200AllOf';

export type GetApiV10IndustryId200 = ApiResponse & GetApiV10IndustryId200AllOf;
