/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetApiV10VideoId200AllOf } from './getApiV10VideoId200AllOf';

export type GetApiV10VideoId200 = ApiResponse & GetApiV10VideoId200AllOf;
