/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetApiV10CaseStudyId200AllOf } from './getApiV10CaseStudyId200AllOf';

export type GetApiV10CaseStudyId200 = ApiResponse & GetApiV10CaseStudyId200AllOf;
