/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetApiV10ContactId200AllOf } from './getApiV10ContactId200AllOf';

export type GetApiV10ContactId200 = ApiResponse & GetApiV10ContactId200AllOf;
