/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PermissionModule } from './permissionModule';

export type GetApiV10Permission200 = {
  success?: boolean;
  data?: PermissionModule[];
};
