/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetCareerId200AllOf } from './getCareerId200AllOf';

export type GetCareerId200 = ApiResponse & GetCareerId200AllOf;
