/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetIndustryId200AllOf } from './getIndustryId200AllOf';

export type GetIndustryId200 = ApiResponse & GetIndustryId200AllOf;
