/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { GetPostIdHistory200AllOfResponseDataItem } from './getPostIdHistory200AllOfResponseDataItem';

export type GetPostIdHistory200AllOf = {
  responseData?: GetPostIdHistory200AllOfResponseDataItem[];
};
