/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetSolutionId200AllOf } from './getSolutionId200AllOf';

export type GetSolutionId200 = ApiResponse & GetSolutionId200AllOf;
