/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface IndustryUpdate {
  /** @maxLength 255 */
  slug?: string;
  /** @maxLength 255 */
  name?: string;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  icon_id?: string | null;
  /** @nullable */
  thumbnail_id?: string | null;
  sort_order?: number;
  is_active?: boolean;
  /**
   * @maxLength 255
   * @nullable
   */
  meta_title?: string | null;
  /** @nullable */
  meta_description?: string | null;
}
