/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface LeadershipUpdate {
  /** @maxLength 255 */
  slug?: string;
  /** @maxLength 255 */
  name?: string;
  /**
   * @maxLength 255
   * @nullable
   */
  position?: string | null;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  photo_id?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  email?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  linkedin?: string | null;
  sort_order?: number;
  is_active?: boolean;
}
