/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PartnerPartnerType } from './partnerPartnerType';

export interface Partner {
  id: string;
  /** @maxLength 255 */
  slug: string;
  /** @maxLength 255 */
  name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  logo_id?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  website?: string | null;
  partner_type: PartnerPartnerType;
  sort_order: number;
  is_active: boolean;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  updated_at: string;
  /** @nullable */
  updated_by?: string | null;
}
