/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PatchApiV10TagId200AllOf } from './patchApiV10TagId200AllOf';

export type PatchApiV10TagId200 = ApiResponse & PatchApiV10TagId200AllOf;
