/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PermissionAction } from './permissionAction';
import type { PermissionModule } from './permissionModule';

/**
 * Static permission registry từ constants/permissions (không lưu DB)
 */
export interface PermissionCatalog {
  rows?: PermissionAction[];
  count?: number;
  structured?: PermissionModule[];
}
