/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthForgotPasswordRequestBody = {
  email: string;
  /** Ghi chú thêm từ user (tên, lý do, etc.) */
  note?: string;
};
