/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type PostPostCategoryPostIdBulkBody = {
  category_ids?: string[];
  created_by?: string;
};
