/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthRefreshBodyDeviceInfo } from './postAuthRefreshBodyDeviceInfo';

export type PostAuthRefreshBody = {
  /** Refresh token (optional if sent via cookie) */
  refresh_token?: string;
  /** Device information */
  device_info?: PostAuthRefreshBodyDeviceInfo;
};
