/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostApiV10PostTagPostIdBulk200AllOf } from './postApiV10PostTagPostIdBulk200AllOf';

export type PostApiV10PostTagPostIdBulk200 = ApiResponse & PostApiV10PostTagPostIdBulk200AllOf;
