/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostCaseStudy200AllOf } from './postCaseStudy200AllOf';

export type PostCaseStudy200 = ApiResponse & PostCaseStudy200AllOf;
