/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostIndustry200AllOf } from './postIndustry200AllOf';

export type PostIndustry200 = ApiResponse & PostIndustry200AllOf;
