/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type PostUpdateReleaseMode = typeof PostUpdateReleaseMode[keyof typeof PostUpdateReleaseMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUpdateReleaseMode = {
  NOW: 'NOW',
  SCHEDULED: 'SCHEDULED',
} as const;
