/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PostPostCategory200AllOfResponseData } from './postPostCategory200AllOfResponseData';

export type PostPostCategory200AllOf = {
  responseData?: PostPostCategory200AllOfResponseData;
};
