/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthLogin423Error } from './postAuthLogin423Error';

export type PostAuthLogin423 = {
  success?: boolean;
  error?: PostAuthLogin423Error;
};
