/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type PostCreateReleaseMode = typeof PostCreateReleaseMode[keyof typeof PostCreateReleaseMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCreateReleaseMode = {
  NOW: 'NOW',
  SCHEDULED: 'SCHEDULED',
} as const;
