/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { Industry } from './industry';

export type PostApiV10Industry200AllOf = {
  responseData?: Industry;
};
