/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostPartner200AllOf } from './postPartner200AllOf';

export type PostPartner200 = ApiResponse & PostPartner200AllOf;
