/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PostPostTagPostIdBulk200AllOfResponseDataItem } from './postPostTagPostIdBulk200AllOfResponseDataItem';

export type PostPostTagPostIdBulk200AllOf = {
  responseData?: PostPostTagPostIdBulk200AllOfResponseDataItem[];
};
