/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostApiV10PostCategoryPostIdBulk200AllOf } from './postApiV10PostCategoryPostIdBulk200AllOf';

export type PostApiV10PostCategoryPostIdBulk200 = ApiResponse & PostApiV10PostCategoryPostIdBulk200AllOf;
