/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type ProductUpdateCategory = typeof ProductUpdateCategory[keyof typeof ProductUpdateCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductUpdateCategory = {
  ENTERPRISE: 'ENTERPRISE',
  AI: 'AI',
  COMMERCE: 'COMMERCE',
  INDUSTRY: 'INDUSTRY',
} as const;
