/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ProductCategory } from './productCategory';

export interface Product {
  id: string;
  /** @maxLength 255 */
  slug: string;
  /** @maxLength 255 */
  name: string;
  category: ProductCategory;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  thumbnail_id?: string | null;
  /** @nullable */
  solution_id?: string | null;
  /** @nullable */
  industry_id?: string | null;
  sort_order: number;
  is_featured: boolean;
  is_active: boolean;
  /**
   * @maxLength 255
   * @nullable
   */
  meta_title?: string | null;
  /** @nullable */
  meta_description?: string | null;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  updated_at: string;
  /** @nullable */
  updated_by?: string | null;
}
