/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type ProductCategory = typeof ProductCategory[keyof typeof ProductCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductCategory = {
  ENTERPRISE: 'ENTERPRISE',
  AI: 'AI',
  COMMERCE: 'COMMERCE',
  INDUSTRY: 'INDUSTRY',
} as const;
