/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutApiV10LeadershipId200AllOf } from './putApiV10LeadershipId200AllOf';

export type PutApiV10LeadershipId200 = ApiResponse & PutApiV10LeadershipId200AllOf;
