/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutApiV10IndustryId200AllOf } from './putApiV10IndustryId200AllOf';

export type PutApiV10IndustryId200 = ApiResponse & PutApiV10IndustryId200AllOf;
