/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutApiV10CareerId200AllOf } from './putApiV10CareerId200AllOf';

export type PutApiV10CareerId200 = ApiResponse & PutApiV10CareerId200AllOf;
