/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV10RoleIdPermissionBodyPermissionsItem } from './putApiV10RoleIdPermissionBodyPermissionsItem';

export type PutApiV10RoleIdPermissionBody = {
  permissions?: PutApiV10RoleIdPermissionBodyPermissionsItem[];
};
