/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutCaseStudyId200AllOf } from './putCaseStudyId200AllOf';

export type PutCaseStudyId200 = ApiResponse & PutCaseStudyId200AllOf;
