/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PutPartnerId200AllOf } from './putPartnerId200AllOf';

export type PutPartnerId200 = ApiResponse & PutPartnerId200AllOf;
