/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { Response } from './response';
import type { ResponseGetAllDataAllOf } from './responseGetAllDataAllOf';

export type ResponseGetAllData = Response & ResponseGetAllDataAllOf;
