/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { RolePermissionItem } from './rolePermissionItem';
import type { _RoleCount } from './_roleCount';

export interface Role {
  id: string;
  /** @maxLength 100 */
  name: string;
  /**
   * @maxLength 500
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  created_at?: string | null;
  /** @nullable */
  updated_at?: string | null;
  /** @nullable */
  created_by?: string | null;
  /** @nullable */
  updated_by?: string | null;
  /** Danh sách permissions dạng {module, action} */
  permissions?: RolePermissionItem[];
  /** Số lượng user đang có role và số permission đã gán */
  _count?: _RoleCount;
}
