/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { RolePermissionItem } from './rolePermissionItem';

export interface RoleUpdate {
  /** @maxLength 100 */
  name?: string;
  /**
   * @maxLength 500
   * @nullable
   */
  description?: string | null;
  /** Danh sách permissions dạng {module, action} (ghi đè toàn bộ permissions hiện tại) */
  permissions?: RolePermissionItem[];
}
