/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { SolutionUpdateType } from './solutionUpdateType';

export interface SolutionUpdate {
  /** @maxLength 255 */
  slug?: string;
  /** @maxLength 255 */
  title?: string;
  type?: SolutionUpdateType;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  icon_id?: string | null;
  /** @nullable */
  thumbnail_id?: string | null;
  sort_order?: number;
  is_featured?: boolean;
  is_active?: boolean;
  /** @nullable */
  industry_ids?: string[] | null;
  /**
   * @maxLength 255
   * @nullable
   */
  meta_title?: string | null;
  /** @nullable */
  meta_description?: string | null;
}
