/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type SolutionType = typeof SolutionType[keyof typeof SolutionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SolutionType = {
  BUSINESS: 'BUSINESS',
  TECHNOLOGY: 'TECHNOLOGY',
  TALENT: 'TALENT',
} as const;
