/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { TermPositionRequestItem } from './termPositionRequestItem';

export interface TermUpdateRequest {
  name?: string;
  start_date?: string;
  end_date?: string;
  /** @minItems 1 */
  positions?: TermPositionRequestItem[];
}
