/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { TermPositionResponse } from './termPositionResponse';

export interface TermResponse {
  term_id: string;
  name: string;
  start_date: string;
  end_date: string;
  positions: TermPositionResponse[];
}
