/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface TermPositionRequestItem {
  position_id: string;
  /** @minItems 1 */
  member_ids: string[];
}
