/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { TermMemberAvatar } from './termMemberAvatar';

/**
 * @nullable
 */
export type TermMemberAvatarProperty = TermMemberAvatar | null;
