/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { UserMeResponsePermissionsItem } from './userMeResponsePermissionsItem';

export interface UserMeResponse {
  id?: string;
  email?: string;
  username?: string;
  /** @nullable */
  first_name?: string | null;
  /** @nullable */
  last_name?: string | null;
  status?: string;
  created_at?: string;
  updated_at?: string;
  roles?: string[];
  permissions?: UserMeResponsePermissionsItem[];
}
