/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { UserUpdateType } from './userUpdateType';
import type { UserUpdateGender } from './userUpdateGender';

export interface UserUpdate {
  username?: string;
  first_name?: string;
  last_name?: string;
  phone?: string;
  avatar_id?: string;
  type?: UserUpdateType;
  birth_date?: string;
  /** @nullable */
  hometown?: string | null;
  gender?: UserUpdateGender;
  /** @nullable */
  bio?: string | null;
}
